// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnSSWQzvp3TlYiIiFB1N2Urbeb_q9qrqU',
    appId: '1:620727561692:web:b139a0137b2104dc80f319',
    messagingSenderId: '620727561692',
    projectId: 'to-do-list-6da7b',
    authDomain: 'to-do-list-6da7b.firebaseapp.com',
    storageBucket: 'to-do-list-6da7b.appspot.com',
    measurementId: 'G-Z33SF2P2HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAljbswEzoXJVV2jVYnV1Fi9isFotWcWu4',
    appId: '1:620727561692:android:ff910a8f3d7052ae80f319',
    messagingSenderId: '620727561692',
    projectId: 'to-do-list-6da7b',
    storageBucket: 'to-do-list-6da7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_UwUUSTMsq0erLHZKgBS-cpa8H1Iuek',
    appId: '1:620727561692:ios:451abc70515ea2e480f319',
    messagingSenderId: '620727561692',
    projectId: 'to-do-list-6da7b',
    storageBucket: 'to-do-list-6da7b.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );
}
